# Generated by Django 3.1.4 on 2020-12-02 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allcourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=200)),
                ('instructorname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfpaced', models.CharField(max_length=700)),
                ('Instructorlead', models.CharField(max_length=700)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoderBase.allcourse')),
            ],
        ),
    ]
