# Generated by Django 3.1.2 on 2020-12-02 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoderBase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allcourse',
            old_name='coursename',
            new_name='courseName',
        ),
        migrations.RenameField(
            model_name='allcourse',
            old_name='instructorname',
            new_name='instructorName',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='Instructorlead',
            new_name='InstructorLead',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='selfpaced',
            new_name='selfPaced',
        ),
    ]
