# Generated by Django 3.1.2 on 2020-12-02 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoderBase', '0002_auto_20201203_0035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allcourse',
            old_name='courseName',
            new_name='CourseName',
        ),
        migrations.RenameField(
            model_name='allcourse',
            old_name='instructorName',
            new_name='InstructorName',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='selfPaced',
            new_name='SelfPaced',
        ),
    ]
